In [4]:
import numpy as np

threshold = 0.0000000000001
beta =0.85

'''
# Our Good Network
A=[[0,0,1,0],
   [1,0,0,1],
   [1,1,0,1],
   [1,0,0,0]]
'''

# Our Spider Trap Network
A=[[0,0,1,0],
   [1,0,0,0],
   [1,1,0,0],
   [1,1,0,1]]

arr=np.array(A, dtype=float)

s=[]

for i in range(0, len(A)):
    s.append(np.sum(arr[:,i]))



print("Summation of columns: ", s)   

M=arr

for j in range(0, len(A)):
    M[:,j]=M[:,j]/s[j]

print("Column stochastic probability matrix, M:")
print(M)

r=(1.0+np.zeros([len(M), 1]))/len(M)

print("Initial rank vector:")
print(r)

uniformR=(1.0-beta)*r

r_prev=r

for i in range(1, 1001):
    print("Iteration: ", i)
    r=beta*np.matmul(M, r_prev)+uniformR
    
    print("The rank vector: ")
    print(r)
    
    diff=np.sum(abs(r-r_prev))
    if (diff<threshold):
        break
    
    r_prev=r

print("The final rank vector: ")
print(r[:, 0])

Summation of columns:  [3.0, 2.0, 1.0, 1.0]
Column stochastic probability matrix, M:
[[0.         0.         1.         0.        ]
 [0.33333333 0.         0.         0.        ]
 [0.33333333 0.5        0.         0.        ]
 [0.33333333 0.5        0.         1.        ]]
Initial rank vector:
[[0.25]
 [0.25]
 [0.25]
 [0.25]]
Iteration:  1
The rank vector: 
[[0.25      ]
 [0.10833333]
 [0.21458333]
 [0.42708333]]
Iteration:  2
The rank vector: 
[[0.21989583]
 [0.10833333]
 [0.154375  ]
 [0.51739583]]
Iteration:  3
The rank vector: 
[[0.16871875]
 [0.09980382]
 [0.14584549]
 [0.58563194]]
Iteration:  4
The rank vector: 
[[0.16146866]
 [0.08530365]
 [0.12772027]
 [0.62550742]]
Iteration:  5
The rank vector: 
[[0.14606223]
 [0.08324945]
 [0.1195035 ]
 [0.65118481]]
Iteration:  6
The rank vector: 
[[0.13907798]
 [0.0788843 ]
 [0.11426532]
 [0.66777241]]
Iteration:  7
The rank vector: 
[[0.13462552]
 [0.07690543]
 [0.11043125]
 [0.6780378 ]]
Iteration:  8
The rank vector: 
[[0.13136657]
 [0